[package]
name = "rusty_jam"
version = "0.1.0"
authors = ["Agnishom Chattopadhyay <cagnishom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"